main:
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Research
    url: '#projects'
    weight: 20
  - name: Talks
    url: '#talks'
    weight: 40
  - name: GitHub
    url: 'https://github.com/PBarkema'
    weight: 50
